webapp1:
    build: ./webapp
    expose: 
      - "8080"
    volumes:
      - ./webapp:/app

webapp2:
    build: ./webapp
    expose:
      - "8080"
    volumes:
      - ./webapp:/app

caddy:
  image: registry.cn-hangzhou.aliyuncs.com/lizi/caddy
  ports:
    - "80:80"
  volumes:
    - ./Caddyfile:/etc/Caddyfile
  links:
    - webapp1
    - webapp2
  

